package com.zepto.product.entity;



import java.beans.ConstructorProperties;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;


/**
 * JPA Entity class representing the "product_entity" table in the MySQL database.
 *
 * Annotated with @Entity to mark this class as a Hibernate-managed persistent object.
 * Hibernate will automatically map this class to a corresponding database table,
 * and each field maps to a column in that table.
 *
 * Table Mapping:
 *     Class Name   : ProductEntity
 *     Default Table: "product_entity" (Hibernate derives table name from class name)
 *     To customize : Add @Table(name = "products") above the class
 *
 * Layer Role   : Entity / Model Layer (Persistence Layer)
 * Managed By   : Hibernate SessionFactory
 * Connected To : zepto_db MySQL database (configured in spring-config.xml)
 *
 * Schema (auto-generated by Hibernate based on hbm2ddl.auto=update):
 * ┌──────────────────────────────────────┐
 * │           product_entity             │
 * ├─────────────┬────────────────────────┤
 * │ product_id  │ VARCHAR (Primary Key)  │
 * │ name        │ VARCHAR                │
 * └─────────────┴────────────────────────┘
 */
@Entity
@Table(name="product_info")
public class ProductEntity {

    /**
     * The unique identifier for the product.
     *
     * Annotated with @Id to designate this field as the Primary Key
     * of the "product_entity" table.
     *
     * Value is a generated 8-character uppercase alphanumeric string
     * produced by {@link com.zepto.product.repository.ProductRepository#uploadProduct(String)}.
     *
     * Example: "A1B2C3D4"
     *
     * Note: Since the ID is manually assigned (not auto-generated by the DB),
     *       there is no @GeneratedValue annotation here.
     *       If you want the DB to auto-generate IDs, add:
     *       @GeneratedValue(strategy = GenerationType.IDENTITY)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    
    @Column
    private String productId;

 
    /**
     * The name of the product.
     *
     * Annotated with @Column to explicitly map this field to a
     * database column. By default, the column name matches the field name ("name").
     *
     * To customize the column definition, use:
     *     @Column(name = "product_name", nullable = false, length = 255)
     *
     * Example: "Laptop"
     */
    @Column
    private String name;
    
    @Column
    private String status;

    @Column
    private String approvalNote; 
    
    @OneToOne(mappedBy = "productEntity", cascade = CascadeType.ALL)
    private PriceEntity price;
    
    
    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Default no-argument constructor required by JPA/Hibernate specification.
     *
     * Hibernate uses reflection to instantiate entity objects when loading
     * records from the database. It requires a no-arg constructor to do so.
     *
     * ⚠️ Do not remove this constructor — Hibernate will throw an
     * InstantiationException at runtime without it.
     */
    public ProductEntity() {

    }

    /**
     * Parameterized constructor for creating a fully populated ProductEntity object.
     * Used when saving a new product record to the database.
     *
     * @param productId The unique 8-character product ID generated by the repository.
     * @param name      The name of the product being uploaded.
     *
     * Usage example:
     *     ProductEntity entity = new ProductEntity("A1B2C3D4", "Laptop");
     *     session.save(entity);
     */
    public ProductEntity(String productId, String name, String status) {
        this.productId = productId;
        this.name = name;
        this.status = status;
    }

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getProductId() {
		return productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getApprovalNote() {
		return approvalNote;
	}

	public void setApprovalNote(String approvalNote) {
		this.approvalNote = approvalNote;
	}

	public PriceEntity getPrice() {
		return price;
	}

	public void setPrice(PriceEntity price) {
		this.price = price;
	}

	
	
    
    
}