spring:
  application:
    name: Notification-Service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification
      auto-offset-reset: earliest

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
